# Generated by Django 6.0.4 on 2026-05-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('product', 'Product'), ('user', 'User'), ('movement', 'Movement'), ('alert', 'Alert'), ('approval', 'Approval'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
