# Generated by Django 6.0.4 on 2026-06-08 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='magasinprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='magasinprofile',
            name='admins',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'admin'}, related_name='admin_magasin_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('product', 'Product'), ('user', 'User'), ('chat', 'Chat'), ('transfer', 'Transfer'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
