# Generated by Django 6.0.4 on 2026-06-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_magasinprofile_user_magasinprofile_admins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='magasinprofile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='magasinprofile',
            name='user',
            field=models.OneToOneField(blank=True, limit_choices_to={'role': 'magasin'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='magasin_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
