# Generated by Django 6.0.4 on 2026-06-09 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_magasinprofile_description_magasinprofile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taille',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
