# Generated by Django 6.0.4 on 2026-05-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chatmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('product', 'Product'), ('user', 'User'), ('chat', 'Chat'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
