# Generated by Django 6.0.5 on 2026-05-19 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_product_options_remove_product_magasin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='magasin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.magasinprofile'),
        ),
    ]
