# Generated by Django 6.0.4 on 2026-06-09 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_taille_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
