# Generated by Django 6.0.4 on 2026-05-21 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_movement_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='new_shell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='new_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='previous_shell_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='previous_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='movement',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
