version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: stock_postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile.django
    container_name: stock_backend
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    entrypoint: ["/app/docker-entrypoint.sh"]
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "Stock.asgi:application"]
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: stock_frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
